name: package-macos

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'  # Trigger on all tags like v1.0.0, v2.1.0-beta
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.2.3 or v1.2.3-beta)'
        required: true
        type: string

jobs:
  # package macos app, we perform following steps here:
  # - build the app at Aurora.app
  # - perform ad-hoc code signing to prevent app broken error (as we do not sign or notarize as of now)
  # - remove gatekeeper quarantine attributes to prevent app broken error (as we do not sign or notarize as of now)
  # - create zip file out of updated Aurora.app file
  # these steps are not required if decide to sign and notarize the app in the future
  build:
    runs-on: macos-latest

    outputs:
      artifact_name: ${{ steps.set-artifact.outputs.artifact_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Package macOS App
        run: |
          yarn package:mac
          codesign --deep --force --sign - "release/mac-arm64/Aurora.app"
          xattr -rd com.apple.quarantine "release/mac-arm64/Aurora.app"
          ditto -c -k --sequesterRsrc --keepParent "release/mac-arm64/Aurora.app" "release/mac-arm64/Aurora.zip"

      # gets the branch name and uploads an artifact
      # branch name gets sanitized and artifacts gets uploaded for the branch with format - macos-build-<branch-name>
      - name: Extract branch name
        id: set-artifact
        run: |
          RAW_BRANCH="${{ github.head_ref || github.ref_name }}"
          SAFE_BRANCH=$(echo "$RAW_BRANCH" | sed 's#[^a-zA-Z0-9_.-]#-#g')

          ARTIFACT_NAME="macos-build-${SAFE_BRANCH}"
          echo "artifact_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT

      - name: Upload GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact.outputs.artifact_name }}
          path: release/mac-arm64/Aurora.zip
          overwrite: true

  # runs when running on tag or manually (via dispatch), gets the version name from tag or input and publishes a release
  # if tag uses a suffix (like: v2.1.0-beta, v3.0.0-rc.1) it will publish a prerelease
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: ./release

      - name: Extract version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.version }}"
          else
            TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV

          if [[ "$TAG" == *-* ]]; then
            echo "PRERELEASE=true" >> $GITHUB_ENV
          else
            echo "PRERELEASE=false" >> $GITHUB_ENV
          fi

      - name: Ensure tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git fetch --tags
          if git rev-parse "${{ github.event.inputs.version }}" >/dev/null 2>&1; then
            echo "Tag already exists."
          else
            git tag ${{ github.event.inputs.version }}
            git push origin ${{ github.event.inputs.version }}
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: ${{ env.PRERELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename release artifact
        run: |
          mv ./release/Aurora.zip ./release/Aurora-macos-arm64-${{ env.TAG_NAME }}.zip

      - name: Upload package to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ./release/Aurora-macos-arm64-${{ env.TAG_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
